
package webServices.test;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductServices", targetNamespace = "http://webServices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductServices {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteProduct", targetNamespace = "http://webServices/", className = "webServices.test.DeleteProduct")
    @ResponseWrapper(localName = "deleteProductResponse", targetNamespace = "http://webServices/", className = "webServices.test.DeleteProductResponse")
    @Action(input = "http://webServices/ProductServices/deleteProductRequest", output = "http://webServices/ProductServices/deleteProductResponse")
    public void deleteProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<webServices.test.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllProducts", targetNamespace = "http://webServices/", className = "webServices.test.GetAllProducts")
    @ResponseWrapper(localName = "getAllProductsResponse", targetNamespace = "http://webServices/", className = "webServices.test.GetAllProductsResponse")
    @Action(input = "http://webServices/ProductServices/getAllProductsRequest", output = "http://webServices/ProductServices/getAllProductsResponse")
    public List<Product> getAllProducts();

    /**
     * 
     * @param arg0
     * @return
     *     returns webServices.test.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductById", targetNamespace = "http://webServices/", className = "webServices.test.GetProductById")
    @ResponseWrapper(localName = "getProductByIdResponse", targetNamespace = "http://webServices/", className = "webServices.test.GetProductByIdResponse")
    @Action(input = "http://webServices/ProductServices/getProductByIdRequest", output = "http://webServices/ProductServices/getProductByIdResponse")
    public Product getProductById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addProduct", targetNamespace = "http://webServices/", className = "webServices.test.AddProduct")
    @ResponseWrapper(localName = "addProductResponse", targetNamespace = "http://webServices/", className = "webServices.test.AddProductResponse")
    @Action(input = "http://webServices/ProductServices/addProductRequest", output = "http://webServices/ProductServices/addProductResponse")
    public int addProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        Product arg0);

}
